# Generated by Django 2.2.4 on 2019-08-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAusencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausencia', models.CharField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('fecha_desde', models.DateField(verbose_name='Desde')),
                ('fecha_hasta', models.DateField(verbose_name='Hasta')),
                ('numero_dias', models.IntegerField()),
                ('tipo_ausencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tthh.TipoAusencia')),
            ],
        ),
    ]
