# Generated by Django 2.2.4 on 2019-08-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tthh', '0002_auto_20190815_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='nombre_empleado',
        ),
    ]
